apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-server
  namespace: microservice
spec:
  selector:
    matchLabels:
      app: cloud-config-server
  replicas: 1
  template:
    metadata:
      labels:
        app: cloud-config-server
    spec:
      containers:
        - image: 9900718467/cloud-config-server:v2
          name: service
          env:
            - name: REPO_INFO
              valueFrom:
               secretKeyRef:
                name: gitdetails-secret
                key: giturl
            - name: REPO_USERNAME
              valueFrom:
               secretKeyRef:
                name: gitdetails-secret
                key: username
            - name: REPO_TOKEN
              valueFrom:
               secretKeyRef:
                name: gitdetails-secret
                key: password


        
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-config-server
  namespace: microservice
  labels:
    app: cloud-config-server
    service: cloud-config-server
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: cloud-config-server

      